name: mirex_grd

channels:
  - conda-forge
  - pytorch

dependencies:
  - python=3.7
  - cudatoolkit=10
  - ffmpeg==4.3.1
  - sox==14.4.2
  - pip
  - pip:
      - asteroid==0.3.4
      - praat-parselmouth==0.3.3
